" file encoding
set encoding=utf-8
set fileencodings=utf-8,cp950
scriptencoding utf-8

" Plugin ctrlP
set runtimepath^=~/.vim/bundle/ctrlp.vim
" ignores
set wildignore+=*.o,*.obj,*.pyc                " output objects
set wildignore+=*.png,*.jpg,*.gif,*.ico        " image format
set wildignore+=*.swf,*.fla                    " image format
set wildignore+=*.mp3,*.mp4,*.avi,*.mkv        " media format
set wildignore+=*.git*,*.hg*,*.svn*            " version control system
set wildignore+=*sass-cache*
set wildignore+=*.DS_Store
set wildignore+=log/**
set wildignore+=tmp/**

" Plugin NERDTree
set runtimepath^=~/.vim/bundle/nerdtree



"set colorscheme
"colorscheme xoria256
" syntax lightlight
syntax on
" no compatible vi
set nocompatible
" set tabstop/softtabstop   default tabstop=8
set tabstop=8
"set softtabstop=4
set shiftwidth=8
" change line depend on word
set linebreak
" show line number
"set nu
" autoindent
"set ai
" set cindent  (replace ai) can auto open in c/c++
" set cin
set splitright                        " always open vertical split window in the right side
set splitbelow                        " always open horizontal split window below





"show cmd height
set ch=2

"increase search, dynmaic search and highlight
set incsearch
set hlsearch
set ignorecase                        " ignore case when searching
" Will : Change search color
hi Search term=standout ctermfg=0 ctermbg=11 guifg=Blue guibg=Yellow

" unfold (expand)
set nofoldenable

" disable sound on errors
set visualbell
set noerrorbells
set t_vb=
set tm=500

" buftabs
set laststatus=2
let g:buftabs_in_statusline=1
noremap <A-left> :bprev<CR>
noremap <A-right> :bnext<CR>
noremap <F12> :bprev<CR> :bd #<CR>

" add exten tag jump
map [D <C-Left>
map [C <C-Right>
" map! OD <C-Left>
" map! OC <C-Right>
noremap <C-right> <C-]>
noremap <C-left>  <C-t>
noremap <C-e> :cs find e <C-R>=expand("<cword>")<CR><CR>

" Set column line
set colorcolumn=80
highlight ColorColumn ctermbg=0

vmap <F5> :s/\s\+$//<CR>
map <F5> :s/\s\+$//<CR>
" Reflash Cscope
nmap <F8> :!find . \( -path "./*" -and \( -name "*.[chsS]" -o -name "*.mk" -o -name "Kconfig" -o -name "Makefile" -o -name "*.java" -o -name "*.cpp" -o -name "*.lds" \) \) > cscope.file<CR>
	\:!cscope -Rbkq -i cscope.file<CR>
	\:cs reset<CR>

if filereadable("cscope.out")
	cs add cscope.out
	set cst
endif
